export const enum ActionTypes {
  CHANGE_APP_THEME = 'CHANGE_APP_THEME',
  CHANGE_LANGUAGE = 'CHANGE_LANGUAGE',
  TOGGLE_LOADER = 'TOGGLE_LOADER',
  GET_MEDIA_STREAMS = 'GET_MEDIA_STREAMS',
  CHANGE_COUNTRY = 'CHANGE_COUNTRY',
  TOGGLE_LEFT_NAVIGATION = 'TOGGLE_LEFT_NAVIGATION',
  SWITCH_BETWEEN_NETWORK_ID = 'SWITCH_BETWEEN_NETWORK_ID',
}
